apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
spec:
  selector:
    matchLabels:
      control-plane: manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: manager
    spec:
      containers:
        - command:
            - /scylla-operator-autoscaler
          args:
            - operator-autoscaler
          image: operator-autoscaler:latest
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
