before:
  hooks:
    - go mod download
env:
  - CGO_ENABLED=0
builds:
  -
    id: recommender
    binary: recommender
    main: ./cmd/recommender
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goVersion={{.Env.GOVERSION}}"
    goos:
      - linux
    goarch:
      - amd64

  -
    id: updater
    binary: updater
    main: ./cmd/updater
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goVersion={{.Env.GOVERSION}}"
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - '${RECOMMENDER_IMG}:latest'
      - '${RECOMMENDER_IMG}:{{ .Tag }}'
    builds:
      - recommender
    binaries:
      - recommender
    skip_push: auto
    dockerfile: cmd/recommender/Dockerfile

  - image_templates:
      - '${UPDATER_IMG}:latest'
      - '${UPDATER_IMG}:{{ .Tag }}'
    builds:
      - updater
    binaries:
      - updater
    skip_push: auto
    dockerfile: cmd/updater/Dockerfile
