before:
  hooks:
    - go mod download
env:
  - CGO_ENABLED=0
builds:
  -
    id: recommender
    binary: recommender
    main: ./cmd/recommender
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goVersion={{.Env.GOVERSION}}"
    goos:
      - linux
    goarch:
      - amd64
  -
    id: updater
    binary: updater
    main: ./cmd/updater
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goVersion={{.Env.GOVERSION}}"
    goos:
      - linux
    goarch:
      - amd64
  -
    id: admission-controller
    binary: admission-controller
    main: ./cmd/admission-controller
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goVersion={{.Env.GOVERSION}}"
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates:
      - 'cezarybednarz/scylla-operator-autoscaler-recommender:latest'
      - 'cezarybednarz/scylla-operator-autoscaler-recommender:{{ .Tag }}'
    builds:
      - recommender
    binaries:
      - recommender
    skip_push: auto
    dockerfile: cmd/recommender/Dockerfile
  - image_templates:
      - 'cezarybednarz/scylla-operator-autoscaler-updater:latest'
      - 'cezarybednarz/scylla-operator-autoscaler-updater:{{ .Tag }}'
    builds:
      - updater
    binaries:
      - updater
    skip_push: auto
    dockerfile: cmd/updater/Dockerfile
  - image_templates:
      - 'cezarybednarz/scylla-operator-autoscaler-admission-controller:latest'
      - 'cezarybednarz/scylla-operator-autoscaler-admission-controller:{{ .Tag }}'
    builds:
      - admission-controller
    binaries:
      - admission-controller
    skip_push: auto
    dockerfile: cmd/admission-controller/Dockerfile
