apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:admission-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:admission-controller-role
subjects:
  - kind: ServiceAccount
    name: admission-controller-service-account
    namespace: system
