apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:scylla-cluster-actor
rules:
- apiGroups:
    - scylla.scylladb.com
  resources:
    - clusters
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
