apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:scylla-cluster-autoscaler-actor
rules:
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusterautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusterautoscalers/status
  verbs:
  - get
  - patch
  - update