apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaClusterAutoscaler
metadata:
  name: sca-sample
spec:
  targetRef:
    namespace: scylla
    name: simple-cluster
  updatePolicy:
    updateMode: "Auto"
