apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaClusterAutoscaler
metadata:
  name: sca-sample
spec:
  targetRef:
    namespace: scylla
    name: simple-cluster
  updatePolicy:
    updateMode: "Auto"
  scalingRuleGroups:
    test:
      rules:
      - name: test
        metric: scylla_reactor_utilization
        threshold: 70
        instances: 1
        labels:
          app: scylla
  scalingPolicy:
    datacenters:
    - name: us-east-1
      racks:
      - name: us-east-1a
        scalingRuleGroup: test
