apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:recommender-role
rules:
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusterautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusterautoscalers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
