resources:
- recommender.yaml
- rbac
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: recommender
  newName: scyllazimnx/scylla-operator-autoscaler-recommender
  newTag: latest
