apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: recommender
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
  namespace: system
  labels:
    control-plane: recommender
spec:
  selector:
    matchLabels:
      control-plane: recommender
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: recommender
    spec:
      containers:
        - command:
            - /recommender
          args:
            - operator-autoscaler
          image: recommender:latest
          imagePullPolicy: Always
          name: recommender
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
