apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
  namespace: system
  labels:
    control-plane: recommender
spec:
  selector:
    matchLabels:
      control-plane: recommender
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: recommender
    spec:
      serviceAccountName: recommender-service-account
      containers:
        - command:
            - /usr/bin/recommender
          args:
            - recommender
            - --interval=10s
            - --metrics-selector-set=app=kube-prometheus-stack-prometheus
            - --metrics-default-step=60s
          image: recommender:latest
          imagePullPolicy: Always
          name: recommender
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 20m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
